Repository micronaut-projects/micronaut-serialization, pull requests merged in 2022-11, with the labels that each got.

#302 Prepare for next minor release
  gradle.properties
Labels: relates-to: build

#298 Support more leniant enum parsing and support JsonValue on enum methods
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/TokenErrorSpec.groovy
  serde-jackson/src/test/java/io/micronaut/serde/jackson/enumjsonvalue/TokenError.java
  serde-support/src/main/java/io/micronaut/serde/support/serdes/EnumSerde.java
Labels: type: improvement

#311 Serialize LocalDateTime to string always. Fixes #284
  serde-support/src/main/java/io/micronaut/serde/support/serdes/LocalDateTimeSerde.java
  serde-tck/src/main/groovy/io/micronaut/serde/AbstractBasicSerdeCompileSpec.groovy
Labels: type: bug

#316 ci: jdk temurin and cla provenance
  .github/workflows/central-sync.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
Labels: relates-to: build
