Repository micronaut-projects/micronaut-serialization, pull requests merged in 2023-07, with the labels that each got.

#498 [serialization] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: relates-to: build

#506 [serialization] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#515 Serialization to Core 4.0.0
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#523 Fix for JacksonDecoder.decodeKey returning key when there is none
  serde-jackson/src/main/java/io/micronaut/serde/jackson/JacksonDecoder.java
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonGetterSetterSpec.groovy
Labels: type: bug

#529 Field marked as READ_ONLY in JsonUnwrapped should not be writable
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonUnwrappedSpec.groovy
  serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBean.java
Labels: type: improvement

#530 Fix deserialization with nullable constructor argument of type Object
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
  serde-support/src/test/groovy/io/micronaut/serde/support/deserializers/DeserializeSpec.groovy
  serde-support/src/test/java/io/micronaut/serde/support/TestStatus.java
Labels: type: bug

#531 [serialization] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
Labels: relates-to: build
