Repository micronaut-projects/micronaut-serialization, pull requests merged in 2023-05, with the labels that each got.

#447 Upgrade to Micronaut 4 M3
  benchmarks/build.gradle
  build.gradle.kts
  buildSrc/build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.serde-base.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.serde-examples.gradle
  doc-examples/example-bson-java/build.gradle.kts
  doc-examples/example-groovy/build.gradle
  doc-examples/example-java/build.gradle.kts
  doc-examples/example-java/src/test/resources/logback.xml
  doc-examples/example-jsonb-java/build.gradle.kts
  doc-examples/example-kotlin/build.gradle.kts
  gradle/libs.versions.toml
  serde-processor/src/main/java/io/micronaut/serde/processor/SerdeAnnotationVisitor.java
  serde-support/src/main/java/io/micronaut/serde/support/AdditionalSerdes.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/HealthResultDeserializer.java
  serde-support/src/test/groovy/io/micronaut/serde/support/deserializers/HealthResultDeserializerSpec.groovy
  settings.gradle.kts
Labels: type: dependency-upgrade

#457 [serialization] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#459 Support custom serdes for builtin types
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/CustomStringSerdeSpec.groovy
  serde-support/src/main/java/io/micronaut/serde/support/DefaultSerdeRegistry.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/CoreDeserializers.java
  settings.gradle.kts
Labels: type: improvement

#464 [serialization] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#465 [serialization] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#475 [serialization] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
Labels: relates-to: build
