Repository micronaut-projects/micronaut-serialization, pull requests merged in 2023-08, with the labels that each got.

#535 [serialization] Update common files for branch master
  .github/workflows/gradle.yml
Labels: relates-to: build

#527 Support for @JsonDeserialize(builder=..)
  gradle.properties
  gradle/libs.versions.toml
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/builder/BuilderSpec.groovy
  serde-jackson/src/test/java/io/micronaut/serde/jackson/builder/TestBuildMe.java
  serde-jackson/src/test/java/io/micronaut/serde/jackson/builder/TestBuildMe2.java
  serde-processor/src/main/java/io/micronaut/serde/processor/jackson/databind/JsonDeserializeMapper.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/ObjectDeserializer.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/SimpleBuilderDeserializer.java
Labels: type: enhancement

#540 [serialization] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#544 docs: remove unnecessary versions
  src/main/docs/guide/jsonbAnnotations.adoc
  src/main/docs/guide/quickStart.adoc
  src/main/docs/guide/quickStart/bsonQuick.adoc
  src/main/docs/guide/quickStart/jacksonQuick.adoc
  src/main/docs/guide/quickStart/jsonpQuick.adoc
Labels: type: docs

#541 [serialization] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build
