Repository micronaut-projects/micronaut-serialization, pull requests merged in 2023-11, with the labels that each got.

#634 Fix SerdeImport of subtypes
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonSubtypesSpec.groovy
  serde-support/src/main/java/io/micronaut/serde/support/DefaultSerdeIntrospections.java
Labels: type: bug

#646 Support `@Serdeable.Deserializable(as = ...)` on properties
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonSerializeDeserializeSpec.groovy
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
Labels: type: improvement

#648 [serialization] Update common files for branch master
  .github/workflows/release.yml
  .gitignore
  MAINTAINING.md
  SECURITY.md
Labels: relates-to: build

#650 Fix constructor/bean properties and beans with an executable method
  serde-bson/src/test/groovy/io/micronaut/serde/bson/BsonMappingSpec.groovy
  serde-bson/src/test/java/io/micronaut/serde/bson/BookWithConstructor.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
  serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBean.java
  serde-tck/src/main/groovy/io/micronaut/serde/AbstractBasicSerdeSpec.groovy
  serde-tck/src/main/java/io/micronaut/serde/BeanWithExtraMethod.java
Labels: type: bug

#655 Fix consuming null in `DemuxingObjectDecoder`
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/DemuxingObjectDecoder.java
  serde-support/src/test/groovy/io/micronaut/serde/support/deserializers/DemuxingObjectDecoderSpec.groovy
Labels: type: bug

#660 Fix ignore/exclude and order on a renamed property
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonIgnoreAllowSpec.groovy
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonPropertyOrderSpec.groovy
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonTypeInfoSpec.groovy
  serde-processor/src/main/java/io/micronaut/serde/processor/SerdeAnnotationVisitor.java
  serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBean.java
Labels: type: bug

#671 Fix handling of manged/back references
  serde-api/src/main/java/io/micronaut/serde/config/annotation/SerdeConfig.java
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonManagedReferenceSpec.groovy
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonManagedReferenceSpec.groovy
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/SerdeJsonManagedReferenceSpec.groovy
  serde-processor/src/main/java/io/micronaut/serde/processor/SerdeAnnotationVisitor.java
  serde-processor/src/main/java/io/micronaut/serde/processor/jackson/JsonBackReferenceMapper.java
  serde-processor/src/main/java/io/micronaut/serde/processor/jackson/JsonManagedReferenceMapper.java
  test-suite-tck-jackson-databind/src/test/groovy/io/micronaut/serde/tck/jackson/databind/DatabindJsonManagedReferenceSpec.groovy
Labels: type: bug
