Repository micronaut-projects/micronaut-serialization, pull requests merged in 2023-09, with the labels that each got.

#558 Support importing packages / builders
  doc-examples/example-java/build.gradle.kts
  doc-examples/example-java/src/main/java/example/ImportBuilders.java
  doc-examples/example-java/src/test/java/example/SerdeImportBuilderTest.java
  gradle/libs.versions.toml
  serde-api/src/main/java/io/micronaut/serde/LimitingStream.java
  serde-api/src/main/java/io/micronaut/serde/annotation/SerdeImport.java
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonFilterSpec.groovy
  serde-jsonp/src/main/java/io/micronaut/serde/json/stream/JsonParserDecoder.java
  serde-processor/src/main/java/io/micronaut/serde/processor/SerdeAnnotationVisitor.java
  serde-processor/src/main/java/io/micronaut/serde/processor/jackson/databind/JsonDeserializeMapper.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/HealthResultDeserializer.java
  serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBean.java
Labels: type: improvement

#565 [serialization] Update common files for branch master
  .github/workflows/central-sync.yml
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#576 [serialization] Update common files for branch master
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#582 Fix unnesting after WRAPPER_OBJECT subtype deserialization
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/JsonSubtypesSpec.groovy
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/SpecificObjectDeserializer.java
Labels: type: bug

#583 Move SimpleBuilderDeserializer into SpecificObjectDeserializer
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/builder/BuilderSpec.groovy
  serde-jackson/src/test/java/io/micronaut/serde/jackson/builder/TestBuildSubtype.java
  serde-jackson/src/test/java/io/micronaut/serde/jackson/builder/TestBuildSupertype.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/ObjectDeserializer.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/SimpleBuilderDeserializer.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/SpecificObjectDeserializer.java
Labels: type: enhancement

#584 Builder token buffer support
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/builder/BuilderSpec.groovy
  serde-jackson/src/test/java/io/micronaut/serde/jackson/builder/TestBuildSubtype2.java
  serde-jackson/src/test/java/io/micronaut/serde/jackson/builder/TestBuildSupertype2.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/SpecificObjectDeserializer.java
Labels: type: enhancement
