Repository micronaut-projects/micronaut-serialization, pull requests merged in 2024-01, with the labels that each got.

#722 [serialization] Update common files for branch master
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#719 Add ObjectMapper.cloneWithConfiguration
  serde-api/src/main/java/io/micronaut/serde/Deserializer.java
  serde-api/src/main/java/io/micronaut/serde/ObjectMapper.java
  serde-api/src/main/java/io/micronaut/serde/SerdeRegistry.java
  serde-api/src/main/java/io/micronaut/serde/Serializer.java
  serde-jackson/src/main/java/io/micronaut/serde/jackson/JacksonJsonMapper.java
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/ConfigCloneSpec.groovy
  serde-jsonp/src/main/java/io/micronaut/serde/json/stream/JsonStreamMapper.java
  serde-support/src/main/java/io/micronaut/serde/support/DefaultDecoderContext.java
  serde-support/src/main/java/io/micronaut/serde/support/DefaultEncoderContext.java
  serde-support/src/main/java/io/micronaut/serde/support/DefaultSerdeRegistry.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBeanKey.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/ObjectDeserializer.java
  serde-support/src/main/java/io/micronaut/serde/support/serdes/DefaultFormattedTemporalSerde.java
  serde-support/src/main/java/io/micronaut/serde/support/serdes/InetAddressSerde.java
  serde-support/src/main/java/io/micronaut/serde/support/serdes/InstantSerde.java
  serde-support/src/main/java/io/micronaut/serde/support/serdes/LocalDateSerde.java
  serde-support/src/main/java/io/micronaut/serde/support/serdes/LocalDateTimeSerde.java
  serde-support/src/main/java/io/micronaut/serde/support/serdes/LocalTimeSerde.java
  serde-support/src/main/java/io/micronaut/serde/support/serdes/OffsetDateTimeSerde.java
  serde-support/src/main/java/io/micronaut/serde/support/serdes/ZonedDateTimeSerde.java
  serde-support/src/main/java/io/micronaut/serde/support/serializers/ObjectSerializer.java
  serde-support/src/main/java/io/micronaut/serde/support/serializers/OptionalMultiValuesSerializer.java
  serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBean.java
  serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBeanKey.java
Labels: type: improvement

#734 Fix customized map serializer
  serde-support/src/main/java/io/micronaut/serde/support/serializers/CustomizedMapSerializer.java
  serde-support/src/test/groovy/io/micronaut/serde/support/serializers/ObjectWithMapSerializerSpec.groovy
  serde-support/src/test/java/io/micronaut/serde/support/ObjectWithMap.java
Labels: type: bug

#724 [serialization] Update common files for branch master
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build
