Repository micronaut-projects/micronaut-serialization, pull requests merged in 2024-10, with the labels that each got.

#943 Implement JsonView support
  serde-api/src/main/java/io/micronaut/serde/Deserializer.java
  serde-api/src/main/java/io/micronaut/serde/Serializer.java
  serde-api/src/main/java/io/micronaut/serde/config/DefaultSerdeConfiguration.java
  serde-api/src/main/java/io/micronaut/serde/config/SerdeConfiguration.java
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonAliasSpec.groovy
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonCompileSpec.groovy
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonFilterSpec.groovy
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonFormatSpec.groovy
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonGetterSetterSpec.groovy
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonIgnoreAllowSpec.groovy
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonIgnoreSpec.groovy
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonIncludeSpec.groovy
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonManagedReferenceSpec.groovy
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonNamingSpec.groovy
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonPropertyOrderSpec.groovy
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonPropertySpec.groovy
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonRootNameSpec.groovy
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonSerializeDeserializeSpec.groovy
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonSpec.groovy
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonSubtypesSpec.groovy
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonTypeInfoSpec.groovy
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonUnwrappedSpec.groovy
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonValueSpec.groovy
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonViewArgumentSpec.groovy
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonViewSpec.groovy
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/builder/TestBuildMe.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/builder/TestBuildMe2.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/builder/TestBuildName.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/builder/TestBuildSubtype.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/builder/TestBuildSubtype2.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/builder/TestBuildSupertype.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/builder/TestBuildSupertype2.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/jsonvalue/TokenError.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/maps/CustomKey.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/outerinterface/AbstractClassCommandWorking.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/outerinterface/AbstractClassCommandWorkingToo.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/outerinterface/ClassCommandBroken.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/outerinterface/ClassCommandBrokenToo.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/outerinterface/ClassCommandWorking.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/outerinterface/RecordCommandBroken.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/outerinterface/RecordCommandBrokenToo.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/tst/AfterCareStatsEntry.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/tst/Aggregation.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/tst/ClassificationAndStats.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/tst/ClassificationVars.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/tst/MainAggregationVm.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/tst/StatsEntry.java
  serde-jackson/src/main/java/io/micronaut/serde/jackson/JacksonJsonMapper.java
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/SerdeJsonViewArgumentSpec.groovy
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/object/ArraySerdeSpec.groovy
  serde-jsonp/build.gradle.kts
  serde-jsonp/src/main/java/io/micronaut/serde/json/stream/JsonStreamMapper.java
  serde-jsonp/src/test/groovy/io/micronaut/serde/json/stream/JsonpJsonViewArgumentSpec.groovy
  serde-support/build.gradle.kts
  serde-support/src/main/java/io/micronaut/serde/support/DefaultSerdeRegistry.java
  serde-support/src/main/java/io/micronaut/serde/support/util/JsonViewUtil.java
  src/main/docs/guide/jacksonAnnotations.adoc
Labels: type: improvement

#944 Do not wrap IOExceptions in SerdeException
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/ErrorCatchingDeserializer.java
  serde-tck-tests/src/main/java/io/micronaut/serde/tck/tests/JsonSyntaxExceptionTest.java
Labels: type: bug

#955 Unwrapped/nested properties don't work with Builder
  .github/workflows/gradle.yml
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonUnwrappedSpec.groovy
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/builder/introspected/Address.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
Labels: type: bug

#957 [serialization] Update common files for branch 2.11.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build
