Repository micronaut-projects/micronaut-serialization, pull requests merged in 2024-04, with the labels that each got.

#775 Micronaut 4.4 changes
  gradle/libs.versions.toml
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/SpecificObjectDeserializer.java
  serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBean.java
  serde-tck/src/main/groovy/io/micronaut/serde/MockSerdeIntrospections.groovy
  test-suite-http-server-tck-netty/src/test/java/io/micronaut/serde/http/server/tck/netty/NettyHttpServerTestSuite.java
Labels: type: dependency-upgrade

#818 Improve Enum handling parity with Jackson
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonPropertySpec.groovy
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonValueSpec.groovy
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/object/EnumSerdeSpec.groovy
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/collect/CoreCollectionsDeserializers.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/collect/EnumMapDeserializer.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/collect/EnumSetDeserializer.java
  serde-support/src/main/java/io/micronaut/serde/support/serdes/EnumSerde.java
Labels: type: improvement

#826 Fix enums as map keys
  gradle/libs.versions.toml
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonIgnoreSpec.groovy
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/tst/AfterCareStatsEntry.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/tst/Aggregation.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/tst/ClassificationAndStats.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/tst/ClassificationVars.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/tst/MainAggregationVm.java
  serde-jackson-tck/src/main/java/io/micronaut/serde/jackson/tst/StatsEntry.java
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/SerdeJsonIgnoreSpec.groovy
  serde-support/src/main/java/io/micronaut/serde/support/serializers/CustomizedMapSerializer.java
  serde-support/src/test/groovy/io/micronaut/serde/support/serializers/CustomizedMapSerializerSpec.groovy
Labels: type: bug

#830 docs: clarify how to add annotation processor dependencies for Kotlin…
  src/main/docs/guide/quickStart.adoc
Labels: type: docs
