Repository micronaut-projects/micronaut-serialization, pull requests merged in 2024-02, with the labels that each got.

#745 [serialization] Update common files for branch master
  .github/workflows/central-sync.yml
  .github/workflows/release.yml
Labels: relates-to: build

#749 Small improvements, refactoring + more tests
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonPropertySpec.groovy
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/SerdeImportSpec.groovy
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/SerdeJsonPropertySpec.groovy
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/SpecificObjectDeserializer.java
Labels: type: improvement

#777 Support referencing self in serialize/deserialize as
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonSerializeDeserializeSpec.groovy
  serde-support/src/main/java/io/micronaut/serde/support/DefaultSerdeIntrospections.java
Labels: type: bug

#778 Allow to clone `JacksonJsonMapper` with a different `SerdeJacksonConfiguration`
  serde-jackson/src/main/java/io/micronaut/serde/jackson/JacksonJsonMapper.java
  serde-jackson/src/main/java/io/micronaut/serde/jackson/JacksonObjectMapper.java
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/ConfigCloneSpec.groovy
Labels: type: improvement
