Repository micronaut-projects/micronaut-serialization, pull requests merged in 2025-05, with the labels that each got.

#1091 @JsonIgnoreProperties and others should work on collection types
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonIgnoreSpec.groovy
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/collect/SpecificOnlyCollectionDeserializer.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/collect/SpecificOnlyMapDeserializer.java
  serde-support/src/main/java/io/micronaut/serde/support/serializers/CustomizedMapSerializer.java
  serde-support/src/main/java/io/micronaut/serde/support/serializers/IterableSerializer.java
  serde-support/src/main/java/io/micronaut/serde/support/util/SerdeArgumentConf.java
Labels: type: bug

#1093 More docs
  doc-examples/example-groovy/src/test/groovy/example/BookTest.groovy
  doc-examples/example-java/src/test/java/example/BookTest.java
  doc-examples/example-kotlin-ksp/src/test/kotlin/example/BookTest.kt
  doc-examples/example-kotlin/src/test/kotlin/example/BookTest.kt
Labels: type: docs

#1095 Skip core serdes throwing `NoClassDefFoundError`
  serde-support/src/main/java/io/micronaut/serde/support/DefaultSerdeRegistry.java
Labels: type: improvement

#1096 Tracking of the referenced path for exceptions
  serde-api/src/main/java/io/micronaut/serde/exceptions/InvalidFormatException.java
  serde-api/src/main/java/io/micronaut/serde/exceptions/SerdeException.java
  serde-api/src/main/java/io/micronaut/serde/exceptions/path/CollectionItemReferencePath.java
  serde-api/src/main/java/io/micronaut/serde/exceptions/path/DefaultCollectionItemReferencePath.java
  serde-api/src/main/java/io/micronaut/serde/exceptions/path/DefaultMapItemReferencePath.java
  serde-api/src/main/java/io/micronaut/serde/exceptions/path/DefaultPropertyReferencePath.java
  serde-api/src/main/java/io/micronaut/serde/exceptions/path/MapItemReferencePath.java
  serde-api/src/main/java/io/micronaut/serde/exceptions/path/PropertyReferencePath.java
  serde-api/src/main/java/io/micronaut/serde/exceptions/path/ReferencePath.java
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonExceptionSpec.groovy
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/SerdeJsonExceptionSpec.groovy
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/errors/NoSerdeSpec.groovy
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/SpecificObjectDeserializer.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/collect/ArrayDequeDeserializer.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/collect/ArrayListDeserializer.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/collect/CollectionDeserializer.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/collect/EnumMapDeserializer.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/collect/EnumSetDeserializer.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/collect/HashSetDeserializer.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/collect/LinkedHashSetDeserializer.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/collect/LinkedListDeserializer.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/collect/MapDeserializer.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/collect/StringListDeserializer.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/collect/TreeSetDeserializer.java
  serde-support/src/main/java/io/micronaut/serde/support/serdes/CustomizedObjectArrayDeserializer.java
  serde-support/src/main/java/io/micronaut/serde/support/serdes/CustomizedObjectArraySerializer.java
  serde-support/src/main/java/io/micronaut/serde/support/serializers/CustomizedIterableSerializer.java
  serde-support/src/main/java/io/micronaut/serde/support/serializers/CustomizedMapSerializer.java
  serde-support/src/main/java/io/micronaut/serde/support/serializers/CustomizedObjectSerializer.java
  serde-support/src/main/java/io/micronaut/serde/support/serializers/OptionalMultiValuesSerializer.java
  serde-support/src/main/java/io/micronaut/serde/support/serializers/OptionalValuesSerializer.java
  serde-support/src/main/java/io/micronaut/serde/support/serializers/SerBean.java
  serde-support/src/main/java/io/micronaut/serde/support/serializers/SimpleObjectSerializer.java
  serde-support/src/main/java/io/micronaut/serde/support/serializers/StreamSerializer.java
  serde-support/src/main/java/io/micronaut/serde/support/serializers/StringIterableSerializer.java
  test-suite-tck-jackson-databind/src/test/groovy/io/micronaut/serde/tck/jackson/databind/DatabindJsonExceptionSpec.groovy
Labels: type: improvement

#1097 Support `@JsonInclude(NON_DEFAULT)`
  serde-api/src/main/java/io/micronaut/serde/Serializer.java
  serde-api/src/main/java/io/micronaut/serde/config/annotation/SerdeConfig.java
  serde-jackson-tck/src/main/groovy/io/micronaut/serde/jackson/JsonIncludeSpec.groovy
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/annotation/SerdeJsonIncludeSpec.groovy
  serde-support/src/main/java/io/micronaut/serde/support/serdes/BooleanSerde.java
  serde-support/src/main/java/io/micronaut/serde/support/serdes/ByteSerde.java
  serde-support/src/main/java/io/micronaut/serde/support/serdes/CharSerde.java
  serde-support/src/main/java/io/micronaut/serde/support/serdes/DateSerde.java
  serde-support/src/main/java/io/micronaut/serde/support/serdes/DoubleSerde.java
  serde-support/src/main/java/io/micronaut/serde/support/serdes/FloatSerde.java
  serde-support/src/main/java/io/micronaut/serde/support/serdes/IntegerSerde.java
  serde-support/src/main/java/io/micronaut/serde/support/serdes/LongSerde.java
  serde-support/src/main/java/io/micronaut/serde/support/serdes/ShortSerde.java
  serde-support/src/main/java/io/micronaut/serde/support/serdes/SqlDateSerde.java
  serde-support/src/main/java/io/micronaut/serde/support/serdes/SqlTimestampSerde.java
  serde-support/src/main/java/io/micronaut/serde/support/serializers/CustomizedObjectSerializer.java
  test-suite-tck-jackson-databind/src/test/groovy/io/micronaut/serde/tck/jackson/databind/DatabindJsonIncludeSpec.groovy
Labels: type: improvement
