Repository micronaut-projects/micronaut-serialization, pull requests merged in 2025-01, with the labels that each got.

#999 Sonatype Scan Gradle Plugin
  .github/workflows/gradle.yml
  buildSrc/build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.serde-module.gradle
  gradle/libs.versions.toml
Labels: relates-to: build

#1001 [serialization] Update common files for branch 2.13.x
  .github/workflows/gradle.yml
  gradlew
Labels: relates-to: build

#1021 Fix scenario with generic types in subtypes
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/generic/SerdeGenericSpec.groovy
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/generic/SerdeSpec.groovy
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/generic/V1Namespace.java
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/generic/V1Status.java
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/generic/WatchEvent.java
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/generic/WatchEventError.java
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/generic/WatchEventSuccess.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/SpecificObjectDeserializer.java
Labels: type: improvement

#1030 Favor record constructor over builder for records
  gradle/libs.versions.toml
  serde-jackson/build.gradle.kts
  serde-jackson/src/test/groovy/io/micronaut/serde/jackson/lombok/DeserializeLombokBuilderSpec.groovy
  serde-jackson/src/test/java/io/micronaut/serde/jackson/lombok/CommonDTO.java
  serde-jackson/src/test/java/io/micronaut/serde/jackson/lombok/MyDTO.java
  serde-support/src/main/java/io/micronaut/serde/support/deserializers/DeserBean.java
Labels: type: bug
